Try to fix Docker cache

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -37,7 +37,8 @@ jobs:
         run: |
           DEP_HASH=$(sha256sum yarn.lock | cut -d " " -f1)
           DEPS_IMAGE_TAG=deps-${DEP_HASH}
-          docker pull $IMAGE_NAME:${DEPS_IMAGE_TAG} || docker build --target deps -t $IMAGE_NAME:${DEPS_IMAGE_TAG} .
+          docker pull $IMAGE_NAME:${DEPS_IMAGE_TAG} || echo "deps image not found"
+          docker build --target deps -t $IMAGE_NAME:${DEPS_IMAGE_TAG} .
           docker push $IMAGE_NAME:${DEPS_IMAGE_TAG}
 
       - name: Build Docker image
@@ -80,7 +81,8 @@ jobs:
         run: |
           DEP_HASH=$(sha256sum pom.xml | cut -d " " -f1)
           DEPS_IMAGE_TAG=deps-${DEP_HASH}
-          docker pull $IMAGE_NAME:${DEPS_IMAGE_TAG} || docker build --target deps -t $IMAGE_NAME:${DEPS_IMAGE_TAG} .
+          docker pull $IMAGE_NAME:${DEPS_IMAGE_TAG} || echo "deps image not found"
+          docker build --target deps -t $IMAGE_NAME:${DEPS_IMAGE_TAG} .
           docker push $IMAGE_NAME:${DEPS_IMAGE_TAG}
 
       - name: Build Docker image
